inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Performance:
  Exclude:
    - "spec/**/*"

Rails/AssertNot:
  Include:
    - "spec/**/*"

Rails/RefuteMethods:
  Include:
    - "spec/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Include:
    - "app/**/*"
    - "config/**/*"
    - "lib/**/*"
    - "spec/**/*"
    - "Gemfile"
