service: urbanite

image: pukhanov/urbanite

servers:
  web:
    hosts:
      - <%= ENV['KAMAL_SERVER_IP'] %>
    options:
      "add-host": host.docker.internal:host-gateway
    labels:
      traefik.http.routers.urbanite.rule: Host(`urbanite.pukhanov.ru`)
      traefik.http.routers.urbanite_secure.rule: Host(`urbanite.pukhanov.ru`)
      traefik.http.routers.urbanite_secure.entrypoints: websecure
      traefik.http.routers.urbanite_secure.tls.certresolver: letsencrypt

registry:
  server: cr.selcloud.ru
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "vyacheslav@pukhanov.ru"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

env:
  secret:
    - KAMAL_SERVER_IP
    - KAMAL_REGISTRY_USERNAME
    - KAMAL_REGISTRY_PASSWORD
    - RAILS_MASTER_KEY
